CREATE TABLE miners (
    id INT AUTO_INCREMENT PRIMARY KEY,
    rarity ENUM("COMMON", "UNCOMMON", "RARE", "EPIC", "LEGENDARY", "UNREAL", "LEGACY") DEFAULT "COMMON",
    name VARCHAR(50) NOT NULL,
    description TEXT,
    cells INT NOT NULL DEFAULT 2,
    power BIGINT NOT NULL DEFAULT 0,
    bonus FLOAT NOT NULL DEFAULT 0.0,
    price FLOAT NOT NULL DEFAULT 0.0,
    sellable BOOLEAN NOT NULL DEFAULT TRUE,
    mergeable BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);