CREATE TABLE parts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    rarity ENUM("COMMON", "UNCOMMON", "RARE", "EPIC", "LEGENDARY") DEFAULT "COMMON",
    type ENUM("Hashboard", "Fan", "Wire") DEFAULT "Wire",
    price FLOAT NOT NULL DEFAULT 0.0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);